version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"  
    volumes:
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  
      - prometheus-data:/prometheus  

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin 
    volumes:
      - grafana-storage:/var/lib/grafana 
      - ./provisioning:/etc/grafana/provisioning 
      - ./dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus  

volumes:
  prometheus-data:
  grafana-storage:

