groups:
  - name: application-metrics-alerts
    rules:
      - alert: HighErrorRate
        expr: |
          sum(rate(http_requests_total{status!~"2.."}[5m])) / sum(rate(http_requests_total[5m])) * 100 > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High Error Rate"
          description: "Error rate is above 5% for 5 consecutive minutes."

      - alert: HighLatency
        expr: |
          histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[10m])) by (le)) > 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High p99 Latency"
          description: "p99 latency is above 500ms for 10 consecutive minutes."

      - alert: HighCPUUtilization
        expr: |
          100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Utilization"
          description: "CPU utilization is above 80% for 5 consecutive minutes."

      - alert: LowMemoryAvailable
        expr: |
          100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low Available Memory"
          description: "Memory utilization is above 80% or available memory is below 20%."

