global:
  scrape_interval: 15s  
scrape_configs:
  - job_name: 'node_exporter' 
    static_configs:
      - targets: ['34.159.75.132:9100'] 
  - job_name: 'application_metrics'
    static_configs:
      - targets: ['34.159.75.132:3333']

rule_files:
  - "alert_rules.yml"  

